version: "3.9"

services:
  potonow-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: potonow-web
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - path: .env
        required: false
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://host.docker.internal:8000}
      API_URL: ${API_URL:-http://host.docker.internal:8000}
      NEXT_PUBLIC_AUTH_COOKIE_NAME: ${NEXT_PUBLIC_AUTH_COOKIE_NAME:-access_token}
      AUTH_COOKIE_NAME: ${AUTH_COOKIE_NAME:-access_token}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
